# Use root/example as user/password credentials
version: '3.1'

services:

  local-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3307:3306

  local-test-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3308:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8070:8080