version: '3.1'

services:

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000

  influxdb:
    image: influxdb
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
      - DOCKER_INFLUXDB_INIT_ORG=ntnu
      - DOCKER_INFLUXDB_INIT_BUCKET=glances
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=randomTokenValue
    ports:
      - 8086:8086
